const excuses={
"💼 ОПОЗДАЛ НА РАБОТУ":["Утром пришлось срочно вернуться домой — забыл важную вещь, и понял это уже по дороге.","По дороге попал в сильную пробку из-за аварии, поэтому приехал позже, чем рассчитывал.","Долго ждал транспорт: приложение показывало, что он уже рядом, но автобус в итоге сильно задержался.","Утром неожиданно разболелась голова, пришлось немного прийти в себя, после чего сразу выехал.","Ключи случайно остались внутри квартиры, пришлось ждать помощи, чтобы попасть обратно.","Питомцу утром стало плохо, пришлось срочно разобраться с этим перед выходом.","Рабочие материалы остались дома, пришлось вернуться за ними, иначе приехал бы вообще без нужного.","Утром сломался лифт, а ждать его пришлось дольше, чем я рассчитывал."],
"👥 НЕ ХОЧУ ГУЛЯТЬ С ДРУЗЬЯМИ":["Сегодня совсем нет сил после дня, хочу просто остаться дома и выдохнуть.","У меня внезапно накопились дела, которые сегодня уже нельзя нормально перенести.","Я уже пообещал провести этот вечер с девушкой, поэтому сегодня не смогу присоединиться.","Дома попросили остаться и помочь, так что сегодня я пас.","Завал по учёбе/работе, и если сейчас не сяду за это, завтра будет ещё хуже.","Сегодня вообще не хочется никуда идти — хочу спокойно побыть дома."],
"🎓 ОПОЗДАЛ НА УЧЁБУ":["Проспал будильник и не услышал его с первого раза.","Перед выходом пришлось срочно вернуться домой за важной вещью.","Автобус долго не приезжал, хотя приложение показывало, что он уже рядом.","По дороге попал в пробку из-за аварии.","Перед парой пришлось срочно распечатать материалы, а принтер начал работать с ошибками.","Я вышел вовремя, но пришлось вернуться — забыл ноутбук."],
"📚 НЕ СДАЛ ПРОЕКТ ВОВРЕМЯ":["Почти закончил проект, но при финальной проверке обнаружил ошибки и решил не отправлять недоделанную версию.","Файл с проектом повредился, пришлось восстанавливать последнюю рабочую версию.","Я неправильно понял часть требований и заметил это слишком поздно — пришлось переделывать.","Я недооценил объём работы и понял слишком поздно, что не успеваю закончить всё качественно.","Основную часть закончил вовремя, но не успел нормально проверить и оформить проект перед сдачей.","Перед отправкой обнаружил проблему с несколькими страницами и потратил время на исправление."],
"📱 НЕ ВЗЯЛ ТРУБКУ У МАМЫ/ПАПЫ":["Телефон был на беззвучном, поэтому я не услышал звонки.","Телефон разрядился, только сейчас смог его включить.","Я был в душе и вообще не услышал телефон.","Телефон остался в другой комнате, поэтому не видел звонков.","Был в шумном месте и не услышал, что мне звонили.","Я был за рулём и не мог ответить.","Телефон завис, и я не сразу увидел пропущенные.","Я увидел звонки, но был занят и хотел перезвонить позже, а потом забыл."],
"💔 РАССТАТЬСЯ":["Я понял, что мои чувства уже не такие, как раньше.","Мне кажется, мы стали слишком разными и постоянно смотрим на вещи по-разному.","Я понял, что сейчас не готов к серьёзным отношениям.","Мне нужно время разобраться в себе и своих мыслях.","Я чувствую, что наши отношения больше не делают нас обоих счастливыми.","Между нами стало слишком много недопонимания и ссор.","Я понял, что мы хотим от отношений совершенно разных вещей.","Я больше не чувствую той связи между нами, которая была раньше."],
"💼 ВООБЩЕ НЕ ПРИШЁЛ НА РАБОТУ":["Мой питомец заболел, и сегодня мне нужно остаться с ним и разобраться с ветеринаром.","Ночью прорвало трубу в квартире, утром пришлось ждать аварийную службу и разбираться с последствиями.","У меня срочный визит к врачу, который сегодня уже нельзя перенести.","Мне пришлось срочно ехать в больницу с близким человеком и остаться там.","С машиной возникла серьёзная поломка, её забрали в сервис, а другого способа добраться сегодня нет.","Утром возник срочный семейный вопрос, который невозможно было перенести на другой день.","После кражи со взломом пришлось ждать полицию и специалистов, поэтому сегодня не смогу приехать."]
};
const styleNames={plausible:"Правдоподобная",funny:"Смешная",grand:"Пафосная",pity:"Жалостливая"};
const styles={plausible:{prefix:["Сегодня всё пошло не совсем по плану.","Возникла небольшая накладка, которую пришлось срочно решить."],suffix:["Извини за опоздание, дальше уже буду внимательнее.","Постараюсь, чтобы такое больше не повторилось."]},funny:{prefix:["Короче, сегодня реальность решила устроить мне квест.","С утра всё шло нормально, а потом начался какой-то цирк."],suffix:["В общем, я победил ситуацию, но она взяла реванш по времени.","Да, звучит как отговорка. Потому что это и есть отговорка 😂"]},grand:{prefix:["Сегодня судьба решила испытать меня на прочность.","Есть дни, когда даже самые точные планы склоняются перед обстоятельствами."],suffix:["Но я уже вернулся в строй и готов двигаться дальше.","Это лишь временная задержка на пути к великим свершениям."]},pity:{prefix:["Извини меня, пожалуйста, сегодня действительно всё навалилось одновременно.","Мне очень неловко это говорить, но сегодня день совсем не задался."],suffix:["Надеюсь, ты меня поймёшь и не будешь сильно ругаться.","Мне правда неудобно, что так получилось. 🥺"]}};
let currentCategory=Object.keys(excuses)[0], currentStyle="plausible", lastIndex=-1, currentText="", favorites=JSON.parse(localStorage.getItem("otgovorki_favorites")||"[]");
const $=id=>document.getElementById(id); const categories=$('categories'),topicToggle=$('topicToggle'),selectedTopic=$('selectedTopic'),generateBtn=$('generateBtn'),loadingBox=$('loadingBox'),resultBox=$('resultBox'),excuse=$('excuse'),stats=$('stats'),favoriteBtn=$('favoriteBtn'),copyBtn=$('copyBtn'),anotherBtn=$('anotherBtn'),copyStatus=$('copyStatus'),loadingFill=$('loadingFill'),loadingTitle=$('loadingTitle');
function renderCategories(){categories.innerHTML="";Object.keys(excuses).forEach(c=>{const b=document.createElement("button");b.className="category";b.type="button";b.textContent=c;b.onclick=()=>{currentCategory=c;selectedTopic.textContent=c;categories.classList.add("hidden");topicToggle.classList.remove("open");topicToggle.setAttribute("aria-expanded","false");reset()};categories.appendChild(b)})}
function reset(){lastIndex=-1;resultBox.classList.add("hidden");loadingBox.classList.add("hidden");generateBtn.classList.remove("hidden");currentText="";favoriteBtn.classList.remove("saved");favoriteBtn.textContent="♡"}
function pick(arr){return arr[Math.floor(Math.random()*arr.length)]}
function build(){const list=excuses[currentCategory];let i;do{i=Math.floor(Math.random()*list.length)}while(list.length>1&&i===lastIndex);lastIndex=i;const base=list[i];const s=styles[currentStyle];let text=pick(s.prefix)+" "+base+" "+pick(s.suffix);if(currentStyle==="grand")text=text.replace("Извини за опоздание, ","");return text}
function statData(){const r=()=>Math.floor(45+Math.random()*51);let p={"🧠 Правдоподобность":r(),"😂 Смешность":r(),"🎩 Пафосность":r(),"🥺 Жалостливость":r()};if(currentStyle==="plausible")p["🧠 Правдоподобность"]=Math.max(p["🧠 Правдоподобность"],75);if(currentStyle==="funny")p["😂 Смешность"]=Math.max(p["😂 Смешность"],78);if(currentStyle==="grand")p["🎩 Пафосность"]=Math.max(p["🎩 Пафосность"],78);if(currentStyle==="pity")p["🥺 Жалостливость"]=Math.max(p["🥺 Жалостливость"],78);return p}
function renderStats(){stats.innerHTML="";Object.entries(statData()).forEach(([name,val])=>{const d=document.createElement("div");d.className="stat";d.innerHTML=`<div class="stat-head"><span>${name}</span><b>${val}%</b></div><div class="stat-bar"><div class="stat-fill" style="width:${val}%"></div></div>`;stats.appendChild(d)})}
function updateFav(){const saved=favorites.includes(currentText);favoriteBtn.classList.toggle("saved",saved);favoriteBtn.textContent=saved?"♥":"♡"}
function saveFavorites(){localStorage.setItem("otgovorki_favorites",JSON.stringify(favorites))}
function renderFavorites(){const box=$('favoritesList');box.innerHTML="";if(!favorites.length){box.innerHTML='<div class="empty-favorites">Пока здесь пусто. Нажми ♡ у понравившейся отговорки.</div>';return}favorites.forEach((text,i)=>{const row=document.createElement("div");row.className="favorite-item";row.innerHTML=`<div class="favorite-text">${text}</div><button class="remove-fav" title="Удалить">×</button>`;row.querySelector("button").onclick=()=>{favorites.splice(i,1);saveFavorites();renderFavorites();updateFav()};box.appendChild(row)})}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement("textarea");a.value=text;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}copyStatus.textContent="✓ Скопировано";setTimeout(()=>copyStatus.textContent="",1400)}
async function generate(){generateBtn.classList.add("hidden");resultBox.classList.add("hidden");loadingBox.classList.remove("hidden");loadingFill.style.width="8%";loadingTitle.textContent="Анализируем ситуацию…";$('step1').classList.add("done");$('step2').classList.remove("done");$('step3').classList.remove("done");await new Promise(r=>setTimeout(r,1100));loadingFill.style.width="46%";loadingTitle.textContent=`Подбираем стиль: ${styleNames[currentStyle]}…`;$('step2').classList.add("done");await new Promise(r=>setTimeout(r,1100));loadingFill.style.width="78%";loadingTitle.textContent="Собираем убедительную отговорку…";$('step3').classList.add("done");await new Promise(r=>setTimeout(r,1200));loadingFill.style.width="100%";currentText=build();excuse.textContent=currentText;renderStats();updateFav();loadingBox.classList.add("hidden");resultBox.classList.remove("hidden")}
topicToggle.onclick=()=>{const open=!categories.classList.contains("hidden");categories.classList.toggle("hidden",open);topicToggle.classList.toggle("open",!open);topicToggle.setAttribute("aria-expanded",String(!open))};document.querySelectorAll(".style").forEach(b=>b.onclick=()=>{currentStyle=b.dataset.style;document.querySelectorAll(".style").forEach(x=>x.classList.remove("active"));b.classList.add("active");reset()});generateBtn.onclick=generate;anotherBtn.onclick=generate;copyBtn.onclick=()=>copyText(currentText);excuse.onclick=()=>copyText(currentText);favoriteBtn.onclick=()=>{if(!currentText)return;const i=favorites.indexOf(currentText);if(i>=0)favorites.splice(i,1);else favorites.unshift(currentText);favorites=favorites.slice(0,30);saveFavorites();renderFavorites();updateFav()};$('clearFavorites').onclick=()=>{favorites=[];saveFavorites();renderFavorites();updateFav()};renderCategories();renderFavorites();
